### ISSUE TITLE
Setup CI + Testing

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex-schema-inspector#1]

**Comment by rijkvanzanten** [comment]
@kibertoad Any luck with setting this up?

**Comment by kibertoad** [comment]
Please give me a bit more time :)

**Comment by rijkvanzanten** [comment]
No prob! Didn't know if this was a matter of copy-pasting it from Knex, or if you wanna take some time setting it up cleanly 🙂

**Comment by rijkvanzanten** [comment]
Closed in #19
