### ISSUE TITLE
is_indexed property on columnInfo

### ISSUE THREAD

**Issue by ismail-codar** [knex/knex-schema-inspector#100]
I am using knex-schema-inspector in a code generator. So I need is_indexed property. It can be easly add. 
https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/sqlite.ts#L167 
I can send a PR if it is appropriate.

**Comment by rijkvanzanten** [comment]
Sure thing! Go ahead 🙂

**Comment by ismail-codar** [comment]
I will send in two weeks.

**Comment by ismail-codar** [comment]
Sorry I'm out of interest current time. I am bussy.
