### ISSUE TITLE
Initial feature list

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex-schema-inspector#3]
An in works list of features that would be useful for a schema inspector like this:

### Tables
- [x] List Tables
- [x] Retrieve table (by name)
- [x] Has Table

### Columns
- [ ] List Columns (in table)
- [ ] Retrieve column (by name)
- [ ] Has Column

### (?) Relations
- [ ] List foreign keys

**Comment by gpetrov** [comment]
@rijkvanzanten  Actually I had a pull request on Knex about very similar thing and was suggesting about the same thing, see https://github.com/knex/knex/pull/3835#issuecomment-629611379

But I agree schema retrieval is better off as separate module.

Just committed my latest work, the db queries for schema retrieval might be useful for you.
It took me a while to get them right

See: https://github.com/gpetrov/knex/commit/8654ec0ec2326aa41d47e4bfc49632da8ff6959e

**Comment by rijkvanzanten** [comment]
That's awesome @gpetrov! Thank you so much for the heads up 🙂 

Did you have any other features in mind than the ones listed above?

**Comment by gpetrov** [comment]
Well you can build upon my proposal:

| function | description|
|--|--|
|knex.schema.tables()| to get all tables, with properties
|knex.schema.views()| to get all views
|knex.schema.columns(table)| to get all columns for a table/view

**tables** should return named object with keys:
|property| description|
|--|--|
|engine| the mySQL engine only
|schema| the database schema
|collation| the collation if any mySQL only
|comment| comment for the table if available

**columns** should return named object with keys:
|property| description|
|--|--|
|type|knex type - so integer, string, text
|maxLength| max length of field 
|nullable|nullable
|defaultValue|the default value
|primary|is it a primary key
|increments|is it an autoincrement (created with increments)
|references|the knex references value of the field in other table
|inTable|the referenced table
|onDelete|delete rule if specified
|onUpdate|update rule if specified
|comment|the column comment

**Comment by gpetrov** [comment]
Great progress @rijkvanzanten ! I'm very glad you are picking my proposal and building upon it.

Those schema retrieval queries can be pretty complex and also sometimes slow to execute.
So when fetching a database schema of larger database with like 100+ tables on it, it takes a lot of queries to get it all out and it can takes a several minutes to complete sometimes.

So maybe next to fetching the schema per table, it will be also very useful to fetch the full schema in a single query. This will retrieve all the columns for all tables at once. It will be much faster as you don't have to filter per table and just get all the columns and group them later in JS per table.

So something like: ```knex.schema.getAll()```

You might even consider building a schema cache, so that once full schema is retrieved, the fetching of tables and columns go directly from the cache.

Of course you need to add methods to invalidate that cache or smartly refresh with changes ... some databases do keep timestamps about new changes, so you might be able to get changes in schema only. That will be really amazing to pull off.

**Comment by rijkvanzanten** [comment]
> This will retrieve all the columns for all tables at once. It will be much faster as you don't have to filter per table and just get all the columns and group them later in JS per table.

Very good idea. I might rework the PR to use Knex's query builder instead of putting everything in raw, which in turn allows me to make the `table` parameter of `columns()` optional. That'll allow us to fetch all columns at once, or just a subset of tables 👍 

> You might even consider building a schema cache, so that once full schema is retrieved, the fetching of tables and columns go directly from the cache.

I'm wondering if a cache is something that's in scope of this project. I do agree that something like a cache would be super beneficial for a project like this, but the same applies to Knex as a whole really 🤔 . I think I'd rather focus my efforts on designing a cache wrapper for Knex as a whole, that will use the actual SQL as key with a configurable TTL or something along those lines

**Comment by rijkvanzanten** [comment]
@gpetrov The version on master now works like:

Get all:

```ts
schemaInspector.columns();
```

Get one:

```ts
schemaInspector.columns('articles');
```

**Comment by gpetrov** [comment]
Nice work @rijkvanzanten ! Good idea to go for the Knex queries to retrieve the schema, much better than just using the RAW queries.

It is nicely doable with MySQL as they follow the information schema standard, but I do hope you can pull it off for Postgres as well - the queries there are a very heavy mixture  of information schema and proprietary functions and queries.

And for Oracle it is even worse with their XML queries. MSSQL should be also nicely doable just as MySQL as they do follow the information schema closely.

As for the schema retrieval caching, if you think so global as caching knex queries, I understand that that gets easy out of the scope of this project.

However caching database scheme is very different than just caching regular queries. 
Having the schema and just changes gives you greater advantage later on as it can be combined with automatic migration script generations, depending on the changes.

But lets get the base right first :) so maybe something for the long term

**Comment by rijkvanzanten** [comment]
@gpetrov im not that well versed in all the other database driver types.. would you be able to help setup queries for those that I can then implement into the project? You original work in that PR was already crazy useful to "just plop in" to the structure I set up 🙂

**Comment by gpetrov** [comment]
Sure I will help as much as I can. The programming part is relatively easy indeed, but getting all those databases differences right can be quite challenging and specially also dealing with different versions of the databases as they keep involving.

Having good tests like the one with knex and all the different databases on docker is really a must.
That is the great things about docker - you can have 10 different databases running in no time, just for the tests.

Only oracle is a bit problem, as I can't even got them running on docker. But I'm also not a fan of oracle and their money hungry way of doing business, so you can as well drop them.

Anyway count me in! We can get in touch if you want - I do use Discord chat for most communication - not much of a slack user.

**Comment by elhigu** [comment]
Btw. this might be helpful for extracting foreign keys for postgresql, mysql and mssql https://github.com/sequelize/sequelize-auto/blob/master/lib/dialects/index.js
