### ISSUE TITLE
support for two-part names in MSSQL dialect

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex-schema-inspector#34]
When gathering metadata for existing tables, schema in not always used (for example when using the COLUMNPROPERTY function) and this may lead to incorrect result if tables with same name but different schema are created in the same database

---

_Migrated from https://github.com/directus/directus/issues/3501 by @yorek_

**Comment by rijkvanzanten** [comment]
@yorek would you be able to take a look at https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/mssql.ts ? I'm personally not familiar with MS SQL or it's intricacies 😬

**Comment by yorek** [comment]
Will do. A bit swamped with work, but I'll do it ASAP.
