### ISSUE TITLE
Cannot use schema-inspector in AWS Aurora

### ISSUE THREAD

**Issue by LeifErshag** [knex/knex-schema-inspector#81]
So, my scenario is that i'm running a postgres AWS Aurora RDS database. When trying to use schema-inspector i get:
`"errorMessage": "Error: Unsupported driver used: PostgresClientRDSDataAPI"`
Obviously from [knex-aurora-data-api-client](https://github.com/markusahlstrand/knex-data-api-client)

If i manually change the downloaded NPM package so that it always uses the postgres client it works fine again. But i haven't been able to run a full test-suite on that assumption yet.

**Comment by rijkvanzanten** [comment]
I'm a little confused where that other package comes in 🤔 How are you using this schema inspector package exactly?

For what it's worth, we're currently using it with Aurora Postgres just using the regular `pg` package, so I'm not too sure where that `PostgresClientRDSDataAPI` driver comes from

**Comment by LeifErshag** [comment]
Hmm,

It seems I will have to figure out why the project used knex-aurora-data-api-client from the beginning since... it dosen't seem to be necessary.

Thank you!

Closing.
