### ISSUE TITLE
How to generate migration with this tool?

### ISSUE THREAD

**Issue by hermesalvesbr** [knex/knex-schema-inspector#83]
Hello,

This is possible to generate a migration file with this tool? 

I have a database with sample data, I need to generate the migration tool com structure and sample data for send to git. 

This tool can do this? If not, do you can suggest another one?

Thanks 👍

**Comment by rijkvanzanten** [comment]
Hi @hermesalvesbr! This does _not_ create any migrations of any kind. This library purely allows you to read the schema information from any of Knex's supported databases, which in turn allows for other libraries and tools to do something with that information.
