### ISSUE TITLE
CockroachDB Support

### ISSUE THREAD

**Issue by wodka** [knex/knex-schema-inspector#86]
hi, 

Currently cockroachdb fails in columnInfo. 

https://github.com/directus/directus/discussions/9268#discussioncomment-1707617

**Comment by wodka** [comment]
for me it works with the following modifications:

https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/postgres.ts#L258

```sql
ON pg_catalog.pg_class.oid = CONCAT_WS('.', quote_ident(c.table_schema), quote_ident(c.table_name)):: regclass:: oid
```

**Comment by kibertoad** [comment]
@wodka Would you consider sending a PR with fix? Would be great to also start running tests on CockroachDB as well. You could use configuration from https://github.com/knex/knex/blob/master/scripts/docker-compose.yml for that.

**Comment by kibertoad** [comment]
And probably cockroachdb should be a separate dialect, just like in knex

**Comment by rijkvanzanten** [comment]
@wodka The current implementation was never made to work for CockroachDB specifically. It looks like cockroach is sorta Postgres compatible, but not when it comes to the inner workings and system tables we read from for the schema info. Like @kibertoad mentioned, the ideal way forwards would be to add a dedicated CockroachDB dialect to knex-schema-inspector as well (cc @Oreilles)

**Comment by wodka** [comment]
;) yes - so I'm trying to get it to work with it. Here also comes a PR with a separate dialect for cockroachdb - including test for cockroachdb. (without the line change it fails, with it works)
